---
name: sample
director_uuid: 74cee69e-2cd8-4c99-96c8-f332e4967021

release:
  name: appcloud
  version: 65

compilation:
  workers: 4
  network: default
  cloud_properties:
    ram: 2048
    disk: 8096
    cpu: 4

update:
  canaries: 1
  canary_watch_time: 3000-90000
  update_watch_time: 3000-90000
  max_in_flight: 2
  max_errors: 1

networks:

- name: default
  subnets:
  - reserved:
    - 192.0.2.2 - 192.0.2.9
    - 192.0.2.245 - 192.0.2.254
    static:
    - 192.0.2.10 - 192.0.2.140
    range: 192.0.2.0/24
    gateway: 192.0.2.1
    dns:
    - 192.0.2.245
    - 192.0.2.246
    cloud_properties:
      name: VLAN2220
- name: lb
  subnets:
  - static:
    - 192.168.0.1 - 192.168.0.100
    range: 192.168.0.0/24
    dns:
    - 192.168.0.245
    - 192.168.0.246
    cloud_properties:
      name: VLAN3093

resource_pools:

- name: infrastructure
  network: default
  size: 32
  stemcell:
    name: bosh-stemcell
    version: 0.4.4
  cloud_properties:
    ram: 4096
    disk: 8192
    cpu: 1
  env:
    bosh:
      password: $6$2f6qtRfO$oJOeKk/ZDNb7PWnvMiXDC/HstKiLiZCBHP32KHFVeM9rXgs4W/JJiI4a/eHoddhxJzorLYgi2JUQiOKxZko4M.
      # c1oudc0w - password generated using mkpasswd -m sha-512

- name: deas
  network: default
  size: 4
  stemcell:
    name: bosh-stemcell
    version: 0.4.4
  cloud_properties:
    ram: 4096
    disk: 16384
    cpu: 4
  env:
    bosh:
      password: $6$2f6qtRfO$oJOeKk/ZDNb7PWnvMiXDC/HstKiLiZCBHP32KHFVeM9rXgs4W/JJiI4a/eHoddhxJzorLYgi2JUQiOKxZko4M.
      # c1oudc0w - password generated using mkpasswd -m sha-512

jobs:

- name: debian_nfs_server
  template: debian_nfs_server
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 8192
  networks:
  - name: default
    static_ips:
    - 192.0.2.10

- name: syslog_aggregator
  template: syslog_aggregator
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 600
  networks:
  - name: default
    static_ips:
    - 192.0.2.13

- name: nats
  template: nats
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.11

- name: opentsdb
  template: opentsdb
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 16384
  networks:
  - name: default
    static_ips:
    - 192.0.2.14

- name: collector
  template: collector
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: dashboard
  template: dashboard
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: ccdb_postgres
  template: ccdb_postgres
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 8192
  networks:
  - name: default
    static_ips:
    - 192.0.2.12

- name: uaadb
  template: ccdb_postgres
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 8192
  properties:
    ccdb:
      user: root
      password: aaa39c8e3f34bc201351ba7a
      address: 192.0.2.15
      port: 2544
      dbname: uaa
  networks:
  - name: default
    static_ips:
    - 192.0.2.15

- name: vcap_redis
  template: vcap_redis
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.16

- name: uaa
  template: uaa
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: cloud_controller
  template: cloud_controller
  instances: 2
  resource_pool: infrastructure
  networks:
  - name: default

- name: stager
  template: stager
  instances: 2
  resource_pool: infrastructure
  networks:
  - name: default

- name: routerv2
  template: routerv2
  instances: 2
  resource_pool: infrastructure
  networks:
  - name: default
    default: [dns, gateway]
  - name: lb
    static_ips:
    - 192.168.0.2 - 192.168.0.2

- name: health_manager
  template: health_manager
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.109

- name: dea
  template: dea
  instances: 4
  resource_pool: deas
  networks:
  - name: default

- name: mysql_node
  template: mysql_node
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 800
  networks:
  - name: default
    static_ips:
    - 192.0.2.30

- name: mysql_gateway
  template: mysql_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: mongodb_node
  template: mongodb_node
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 600
  networks:
  - name: default
    static_ips:
    - 192.0.2.40

- name: mongodb_gateway
  template: mongodb_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: redis_node
  template: redis_node
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 600
  networks:
  - name: default
    static_ips:
    - 192.0.2.50

- name: redis_gateway
  template: redis_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: rabbit_node
  template: rabbit_node
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 4096
  networks:
  - name: default
    static_ips:
    - 192.0.2.60

- name: rabbit_gateway
  template: rabbit_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: postgresql_node
  template: postgresql_node
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 650
  networks:
  - name: default
    static_ips:
    - 192.0.2.70

- name: postgresql_gateway
  template: postgresql_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: backup_manager
  template: backup_manager
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.80

- name: service_utilities
  template: service_utilities
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.81

properties:
  domain: cloudfoundry.test

  env: {}

  networks:
    apps: default
    management: default

  nats:
    user: nats
    password: aaa3ij3122
    address: 192.0.2.11
    port: 4222

  ccdb:
    user: ccadmin
    password: aaaBauWauZZb2
    address: 192.0.2.12
    port: 5524
    pool_size: 10
    dbname: appcloud

  cc:
    srv_api_uri: http://api.cloudfoundry.test
    password: aaauuLaap44jadlas2l312lk
    token: aaaf4eaa8c1758f66d5cb7adcb24adb9d7
    use_nginx: true
    new_stager_percent: 25
    new_stager_email_regexp: '.*@vmware.com'
    staging_upload_user: aaafhgjg
    staging_upload_password: AAAfdase9
    allow_registration: true
    uaa:
      enabled: true
      resource_id: cloud_controller
      client_secret: aaaNxRJcx6cpv
    admins:
    - martin@englund.nu

  vcap_redis:
    address: 192.0.2.16
    port: 5454
    password: aaaxbL98RWpwBuUJvKNojnpIcRb1ot2
    maxmemory: 2000000000 # 2GB

  router:
    status:
      port: 8080
      user: aaaUxXlS0pc71wVef
      password: aaamaIf9vPV4mJyBe

  dashboard:
    users:
      - [dash, admin]

  dea:
    max_memory: 4096

  nfs_server:
    address: 192.0.2.10
    network: 192.0.2.0/24

  opentsdb:
    address: 192.0.2.14
    port: 4242

  service_plans:
    mysql:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          allow_over_provisioning: true
          capacity: 200
          max_db_size: 128
          max_long_query: 3
          max_long_tx: 0
          max_clients: 20
    postgresql:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          capacity: 200
          max_db_size: 128
          max_long_query: 3
          max_long_tx: 30
          max_clients: 20
    mongodb:
      free:
        job_management:
          high_water: 3000
          low_water: 100
        configuration:
          allow_over_provisioning: true
          capacity: 200
          quota_files: 4
          max_clients: 500
    redis:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          capacity: 200
          max_memory: 16
          max_swap: 32
          max_clients: 500
    rabbit:
      free:
        job_management:
          low_water: 100
          high_water: 1400
        configuration:
          max_memory_factor: 0.5
          max_clients: 512
          capacity: 200

  mysql_gateway:
    check_orphan_interval: 7200
    token: "0xfeedface"
  mysql_node:
    production: true
    password: aaa13djkas

  redis_gateway:
    token: "0xfeedface"
    check_orphan_interval: 7200
  redis_node:
    command_rename_prefix: sample

  mongodb_gateway:
    check_orphan_interval: 7200
    token: "0xfeedface"
  mongodb_node:
    {}

  rabbit_gateway:
    token: AAA430A8BAED490B1240338DA34B10D
  rabbit_node:
    {}

  postgresql_gateway:
    check_orphan_interval: 7200
    token: aaaeAh4BXFBXwLrrWJCpQTfeDnaCn7m
  postgresql_node:
    production: true

  syslog_aggregator:
    address: 192.0.2.13
    port: 54321

  stager:
    max_staging_duration: 120
    max_active_tasks: 20
    queues:
    - staging

  uaa:
    db:
      user: root
      password: aaa39c8e3f34bc201351ba7a
      address: 192.0.2.15
      port: 2544
      dbname: uaa
    bootstrap:
      username: admin@vmware.com
      # BCrypt::Password.create('foobar', :cost => 8)
      password: $2a$08$4iXvbGvgfC9vhyN7QjXboeK2tlc3dHMQlcWkfHGaHB5aCY.jTZrgy
      given_name: UAA Administrator
      family_name: UAA Administrator
      email: admin@vmware.com
    cc:
      token_secret: aaabxaiC371JM
      client_secret: $2a$08$dahioBqSkqa1AbLvaqkLoe5W0aOPN3Ia9W0xkeB926G.AZJhq1SsK
    batch:
      username: do0H2AKay2jAc
      password: FSCTiplI5Q83n

