---
name: sample
director_uuid: 74cee69e-2cd8-4c99-96c8-f332e4967021

release:
  name: appcloud
  version: 102

compilation:
  workers: 4
  network: default
  cloud_properties:
    ram: 2048
    disk: 8096
    cpu: 4

update:
  canaries: 1
  canary_watch_time: 3000-90000
  update_watch_time: 3000-90000
  max_in_flight: 2
  max_errors: 1

networks:

- name: default
  subnets:
  - range: 192.0.2.0/24
    reserved:
    - 192.0.2.2 - 192.0.2.9
    - 192.0.2.245 - 192.0.2.254
    static:
    - 192.0.2.10 - 192.0.2.140
    gateway: 192.0.2.1
    dns:
    - 192.0.2.245
    - 192.0.2.246
    cloud_properties:
      name: VLAN2220
- name: lb
  subnets:
  - range: 192.168.0.0/24
    static:
    - 192.168.0.1 - 192.168.0.100
    dns:
    - 192.168.0.245
    - 192.168.0.246
    cloud_properties:
      name: VLAN3093

resource_pools:

- name: infrastructure
  network: default
  size: 45
  stemcell:
    name: bosh-stemcell
    version: 0.6.4
  cloud_properties:
    ram: 4096
    disk: 8192
    cpu: 1
  env:
    bosh:
      password: $6$2f6qtRfO$oJOeKk/ZDNb7PWnvMiXDC/HstKiLiZCBHP32KHFVeM9rXgs4W/JJiI4a/eHoddhxJzorLYgi2JUQiOKxZko4M.
      # c1oudc0w - password generated using mkpasswd -m sha-512

- name: deas
  network: default
  size: 4
  stemcell:
    name: bosh-stemcell
    version: 0.6.4
  cloud_properties:
    ram: 8192
    disk: 16384
    cpu: 4
  env:
    bosh:
      password: $6$2f6qtRfO$oJOeKk/ZDNb7PWnvMiXDC/HstKiLiZCBHP32KHFVeM9rXgs4W/JJiI4a/eHoddhxJzorLYgi2JUQiOKxZko4M.
      # c1oudc0w - password generated using mkpasswd -m sha-512

jobs:

- name: debian_nfs_server
  template: debian_nfs_server
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 8192
  networks:
  - name: default
    static_ips:
    - 192.0.2.10

- name: services_nfs
  template: debian_nfs_server
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 8192
  properties:
    debian_nfs_server:
      no_root_squash: true
  networks:
  - name: default
    static_ips:
    - 192.0.2.20

- name: syslog_aggregator
  template: syslog_aggregator
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 600
  networks:
  - name: default
    static_ips:
    - 192.0.2.13

- name: nats
  template: nats
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.11

- name: hbase_slave
  template: hbase_slave
  instances: 3
  resource_pool: infrastructure
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 192.0.2.21 - 192.0.2.23

- name: hbase_master
  template: hbase_master
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 192.0.2.24

- name: opentsdb
  template: opentsdb
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.14

- name: collector
  template: collector
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: dashboard
  template: dashboard
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: ccdb_postgres
  template: postgres
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 192.0.2.12
  properties:
    db: ccdb

- name: uaadb
  template: postgres
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 192.0.2.15
  properties:
    db: uaadb

- name: vcap_redis
  template: vcap_redis
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.16

- name: services_redis
  template: vcap_redis
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 192.0.2.82
  properties:
    vcap_redis:
      port: 3456
      password: aaaFXngo
      maxmemory: 2000000000
      persistence:
        dir: /var/vcap/store/vcap_redis

- name: uaa
  template: uaa
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: acmdb
  template: postgres
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 192.0.2.17
  properties:
    db: acmdb

- name: acm
  template: acm
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.18

- name: cloud_controller
  template: cloud_controller
  instances: 2
  resource_pool: infrastructure
  networks:
  - name: default

- name: stager
  template: stager
  instances: 2
  resource_pool: infrastructure
  networks:
  - name: default

- name: router
  template: router
  instances: 2
  resource_pool: infrastructure
  networks:
  - name: default
    default: [dns, gateway]
  - name: lb
    static_ips:
    - 192.168.0.1 - 192.168.0.2

- name: health_manager
  template: health_manager
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.109

- name: dea
  template: dea
  instances: 4
  resource_pool: deas
  networks:
  - name: default

- name: mysql_node
  template: mysql_node
  instances: 2
  resource_pool: infrastructure
  persistent_disk: 800
  networks:
  - name: default
    static_ips:
    - 192.0.2.30 - 192.0.2.31

- name: mysql_gateway
  template: mysql_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: mongodb_node
  template: mongodb_node
  instances: 2
  resource_pool: infrastructure
  persistent_disk: 4096
  networks:
  - name: default
    static_ips:
    - 192.0.2.40 - 192.0.2.41

- name: mongodb_gateway
  template: mongodb_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: redis_node
  template: redis_node
  instances: 2
  resource_pool: infrastructure
  persistent_disk: 600
  networks:
  - name: default
    static_ips:
    - 192.0.2.50 - 192.0.2.51

- name: redis_gateway
  template: redis_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: rabbit_node
  template: rabbit_node
  instances: 2
  resource_pool: infrastructure
  persistent_disk: 4096
  networks:
  - name: default
    static_ips:
    - 192.0.2.60 - 192.0.2.61

- name: rabbit_gateway
  template: rabbit_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: postgresql_node
  template: postgresql_node
  instances: 2
  resource_pool: infrastructure
  persistent_disk: 650
  networks:
  - name: default
    static_ips:
    - 192.0.2.70 - 192.0.2.71

- name: postgresql_gateway
  template: postgresql_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: vblob_node
  template: vblob_node
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 1024
  networks:
  - name: default
    static_ips:
    - 192.0.2.90

- name: vblob_gateway
  template: vblob_gateway
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default

- name: backup_manager
  template: backup_manager
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.80

- name: service_utilities
  template: service_utilities
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.81

- name: serialization_data_server
  template: serialization_data_server
  instances: 1
  resource_pool: infrastructure
  networks:
  - name: default
    static_ips:
    - 192.0.2.83

properties:
  domain: cloudfoundry.test

  env:

  networks:
    apps: default
    management: default

  nats:
    user: nats
    password: aaa3ij3122
    address: 192.0.2.11
    port: 4222

  uaadb:
    address: 192.0.2.15
    port: 2544
    roles:
    - tag: admin
      name: uaaadmin
      password: aaaDFsddfwer23223wdfWEF
    databases:
    - tag: uaa
      name: uaa

  ccdb:
    address: 192.0.2.12
    port: 5524
    pool_size: 10
    roles:
    - tag: admin
      name: ccadmin
      password: aaaBauWauZZb2
    databases:
    - tag: cc
      name: appcloud

  acmdb:
    address: 192.0.2.17
    port: 2544
    roles:
    - tag: admin
      name: root
      password: aaa0rBVCCDcMlkpQ0SrE9XUj
    databases:
    - tag: acm
      name: acm

  cc:
    srv_api_uri: http://api.cloudfoundry.test
    password: aaauuLaap44jadlas2l312lk
    token: aaaf4eaa8c1758f66d5cb7adcb24adb9d7
    use_nginx: true
    new_stager_percent: 100
    new_stager_email_regexp: '.*@vmware.com'
    staging_upload_user: aaafhgjg
    staging_upload_password: aaafdase9
    allow_registration: true
    uaa:
      enabled: true
      resource_id: cloud_controller
      token_creation_email_filter: [""]
    admins:
    - martin@englund.nu

  vcap_redis:
    address: 192.0.2.16
    port: 5454
    password: aaaxbL98RWpwBuUJvKNojnpIcRb1ot2
    maxmemory: 2000000000 # 2GB

  router:
    status:
      port: 8080
      user: aaaUxXlS0pc71wVef
      password: aaamaIf9vPV4mJyBe

  dashboard:
    users:
      - [b29, admin]

  dea:
    max_memory: 4096

  nfs_server:
    address: 192.0.2.10
    network: 192.0.2.0/24

  hbase_master:
    address: 192.0.2.24
    hbase_master:
      port: 60000
      webui_port: 60010
      heap_size: 1024
    hbase_zookeeper:
      heap_size: 1024
    hadoop_namenode:
      port: 9000

  opentsdb:
    address: 192.0.2.14
    port: 4242

  hbase_slave:
    hbase_regionserver:
      port: 60020
      heap_size: 1024
    addresses:
    - 192.0.2.21
    - 192.0.2.22
    - 192.0.2.23

  service_plans:
    mysql:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          allow_over_provisioning: true
          capacity: 200
          max_db_size: 128
          max_long_query: 3
          max_long_tx: 0
          max_clients: 20
    postgresql:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          capacity: 200
          max_db_size: 128
          max_long_query: 3
          max_long_tx: 30
          max_clients: 20
    mongodb:
      free:
        job_management:
          high_water: 3000
          low_water: 100
        configuration:
          allow_over_provisioning: true
          capacity: 200
          quota_files: 4
          max_clients: 500
    redis:
      free:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          capacity: 200
          max_memory: 16
          max_swap: 32
          max_clients: 500
    rabbit:
      free:
        job_management:
          low_water: 100
          high_water: 1400
        configuration:
          max_memory_factor: 0.5
          max_clients: 512
          capacity: 200
    vblob:
      free:
        job_management:
          low_water: 100
          high_water: 1400
        configuration:
          capacity: 200

  serialization_data_server:
    upload_token: aaaCOGvTlXT7l8IzAgOHxMXurBrG364k
    use_nginx: true
    upload_timeout: 10
    port: 8080
    upload_file_expire_time: 600
    purge_expired_interval: 30

  service_lifecycle:
    download_url: service-serialization.cloudfoundry.test
    mount_point: /var/vcap/service_lifecycle
    tmp_dir: /var/vcap/service_lifecycle/tmp_dir
    resque:
      host: 192.0.2.82
      port: 3456
      password: aaaFXngo
    nfs_server:
      address: 192.0.2.20
      export_dir: /var/vcap/store/shared
    serialization_data_server:
    - 192.0.2.83

  mysql_gateway:
    check_orphan_interval: 7200
    token: "0xfeedface"
    supported_versions: ["5.1"]
    version_aliases:
      current: "5.1"
  mysql_node:
    production: true
    password: aaa13djkas
    supported_versions: ["5.1"]
    default_version: "5.1"

  redis_gateway:
    token: "0xfeedface"
    check_orphan_interval: 7200
    supported_versions: ["2.2"]
    version_aliases:
      current: "2.2"
  redis_node:
    command_rename_prefix: foobar
    supported_versions: ["2.2"]
    default_version: "2.2"

  mongodb_gateway:
    check_orphan_interval: 7200
    token: "0xfeedface"
    supported_versions: ["1.8", "2.0"]
    version_aliases:
      current: "2.0"
      deprecated: "1.8"

  mongodb_node:
    supported_versions: ["1.8", "2.0"]
    default_version: "1.8"

  rabbit_gateway:
    token: AAA430A8BAED490B1240338DA34B10D
    check_orphan_interval: 7200
    supported_versions: ["2.4"]
    version_aliases:
      current: "2.4"
  rabbit_node:
    supported_versions: ["2.4"]
    default_version: "2.4"

  postgresql_gateway:
    check_orphan_interval: 7200
    token: AAAeAh4BXFBXwLrrWJCpQTfeDnaCn7m
    supported_versions: ["9.0"]
    version_aliases:
      current: "9.0"
  postgresql_node:
    production: true
    supported_versions: ["9.0"]
    default_version: "9.0"

  vblob_gateway:
    token: AAA7eeKifuL9iichPohw1eeh5n
    acls:
      wildcards: [*@vmware.com, *@emc.com, *@rbcon.com]
    supported_versions: ["0.51"]
    version_aliases:
      current: "0.51"
  vblob_node:
    vblobd_auth: s3
    nfs_server:
      address: 192.0.2.20
      export_dir: /var/vcap/store/shared
    supported_versions: ["0.51"]
    default_version: "0.51"

  syslog_aggregator:
    address: 192.0.2.13
    port: 54321

  stager:
    max_staging_duration: 120
    max_active_tasks: 20
    queues:
    - staging

  uaa:
    cc:
      token_secret: aaabxaiC371JM
      client_secret: aaaF5DMNDZIfCb9A
    admin:
      client_secret: aaa5fER8evgEisjj
    batch:
      username: aaaH2AKay2jAc
      password: aaaTiplI5Q83n
    login:
      client_secret: aaa5fasdoi872klj

  acm:
    user: aaa8mx8dvsecmbre
    password: aaaI0DBOzXNEtZW6
